CONFIDENCE_THRESHOLD = 0.4

FPS = 30
BUFFER_SECONDS = 10

FIGHT_SPEED_THRESHOLD = 60
FIGHT_DISTANCE_THRESHOLD = 180
FIGHT_MIN_CONSECUTIVE_FRAMES = 8

RESTRICTED_ZONE = [
    (450, 300),
    (640, 300),
    (640, 480),
    (450, 480)
]
import os

FPS = 20

SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")
